name: Deploy to Server

on:
  push:
    branches:
      - main # or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: shivammathur/setup-ssh@v2
        with:
          ssh_key_secret: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          known_hosts: ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            cd /path/to/deploy/directory 
            # Replace with your deployment commands here
            git pull origin main 
            # Or use your preferred deployment strategy 
          "

secrets:
  SSH_PRIVATE_KEY:
    description: Private SSH key for deployment
    required: true
  SSH_USERNAME:
    description: Username for SSH connection
    required: true
  SSH_HOST:
    description: Hostname or IP address of the server
    required: true
